### ISSUE TITLE
Deprecated in CLN v23.02: `commando` JSON commands without an `id`

### ISSUE THREAD

**Issue by tonyaldon** [jb55/lnsocket#23]
I tried `lnsocket/go` with CLN v23.05 and `allow-deprecated-apis=false` and I got the following error:

    {"error":{"code":19536,"message":"missing id field"}}

See [CHANGELOG: 23.02](https://github.com/ElementsProject/lightning/blob/master/CHANGELOG.md#2302---2023-03-01-cbdc-backing-layer).

**Comment by jb55** [comment]
lmk if it works with #21 merged

**Comment by tonyaldon** [comment]
Yes it works with #21.
