### ISSUE TITLE
iOS example?

### ISSUE THREAD

**Issue by Fonta1n3** [jb55/lnsocket#25]
I'd love to use this to to command my cln node. Does Damus use this? Is there any iOS examples?

**Comment by Fonta1n3** [comment]
nevermind I found lnlink, thank you

**Comment by jb55** [comment]
On Wed, Sep 13, 2023 at 08:00:48PM -0700, Fontaine wrote:
>I'd love to use this to to command my cln node. Does Damus use this? Is there any iOS examples?

http://git.jb55.com/lnlink is my ios app that uses commando to talk to CLN nodes

**Comment by jb55** [comment]
On Fri, Sep 15, 2023 at 12:03:20PM -0500, William Casarin wrote:
>On Wed, Sep 13, 2023 at 08:00:48PM -0700, Fontaine wrote:
>>I'd love to use this to to command my cln node. Does Damus use this? Is there any iOS examples?
>
>http://git.jb55.com/lnlink is my ios app that uses commando to talk to CLN nodes

Ooops just saw that you already found it. Let me know if you run into any
issues!

	Will

**Comment by Fonta1n3** [comment]
Thank you! Will do.
