### ISSUE TITLE
iOS Simulator returning an error

### ISSUE THREAD

**Issue by Fonta1n3** [jb55/lnsocket#26]
Hey Will,

Ive got it running in my app fine on an actual device but on simulator I get the error (both in my app and in LNLink):

`In /Users/fontaine/Desktop/Projects/lnlink/lnsocket/target/ios/lnsocket.a(sha256-arm64.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/fontaine/Desktop/Projects/lnlink/lnsocket/target/ios/lnsocket.a'
`

Were you able to get it running on simulator? I'd like to test on `localhost` before I move to a real device. Not sure what I am doing wrong. I tried removing all the non `arm64` binaries but still get the same error.

**Comment by jb55** [comment]
On Fri, Sep 15, 2023 at 06:55:19PM -0700, Fontaine wrote:
>Hey Will,
>
>Ive got it running in my app fine on an actual device but on simulator I get the error (both in my app and in LNLink):
>
>`In /Users/fontaine/Desktop/Projects/lnlink/lnsocket/target/ios/lnsocket.a(sha256-arm64.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/fontaine/Desktop/Projects/lnlink/lnsocket/target/ios/lnsocket.a'
>`
>
>Were you able to get it running on simulator? I'd like to test on `localhost` before I move to a real device. Not sure what I am doing wrong. I tried removing all the non `arm64` binaries but still get the same error.

I don't think it works in the sim because I never figured out how to do
arm64-sim and arm64-non-sim objects in the same archive.

**Comment by Fonta1n3** [comment]
Is LNUrlAuth required? When I copy your hardcoded LNUrlAuth object the log in fails.

`let auth = LNUrlAuth(k1: "k1", tag: "login", url: URL(string: "jb55.com")!, host: "jb55.com")`

Sorry new to this.

**Comment by Fonta1n3** [comment]
I got it working :) But am bypassing LNUrlAuth.. What role does LNUrlAuth play here anyway? Sorry for the newb questions.

**Comment by jb55** [comment]
On Sat, Sep 16, 2023 at 08:59:01PM -0700, Fontaine wrote:
>What role does LNUrlAuth play in LNLink? I have never used it before..

you can login to sites that use "Login with Lightning". Your login will
be securely associated with your lightning node (in a way that can't be
linked to your lightning node)

**Comment by jb55** [comment]
On Sat, Sep 16, 2023 at 08:45:41PM -0700, Fontaine wrote:
>Is LNUrlAuth required? When I copy your hardcoded LNUrlAuth object the log in fails.
>
>`let auth = LNUrlAuth(k1: "k1", tag: "login", url: URL(string: "jb55.com")!, host: "jb55.com")`
>
>Sorry new to this.

This code is just used for Xcode previews. What are you trying to do?

**Comment by Fonta1n3** [comment]
All good that makes perfect sense.
